repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Format Rust code with rustfmt
        entry: cargo fmt --all
        language: rust
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check Rust code with cargo check
        entry: cargo check --all-features
        language: rust
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code with cargo clippy
        entry: cargo clippy --all-features --no-deps -- -D warnings
        language: rust
        types: [rust]
        pass_filenames: false
