[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1.0"
bitflags = "2.12"
ciborium = "0.2"
clap = "4.6"
const-str = "1.1"
core_affinity = "0.8.3"
ctrlc = "3.5"
derive_more = "2.1"
derive-new = "0.7"
dot-structures = "0.1.2"
fastbloom = { version = "0.17", default-features = false }
fluent-uri = "0.4.1"
graphviz-rust = { version = "0.9", default-features = false }
hashbrown = { version = "0.17", default-features = false }
indexmap = "2.14"
itertools = "0.*"
kmp = "0.1.1"
libafl = { version = "0.16", default-features = false }
libafl_bolts = { version = "0.16", default-features = false }
libcasr = "2"
libc = "0.2"
lsp-fuzz = { path = "crates/lsp-fuzz" }
lsp-fuzz-grammars = { path = "crates/lsp-fuzz-grammars" }
lsp-fuzz-tree-sitter-grammar = { path = "crates/lsp-fuzz-tree-sitter-grammar" }
lsp-types = "0.97"
memmap2 = "0.9"
nix = "0.31"
num_cpus = "1.17"
ordermap = "1.2"
os_pipe = "1.2"
rayon = "1.12"
regex = "1.12"
regex-syntax = "0.8"
rustc-hash = "2.1"
serde = "1.0"
serde_json = "1.0"
smallvec = "1.15"
static_assertions = "1.1"
tempfile = "3.27"
thiserror = "2.0"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false }
trait-gen = "2.0.7"
tree-sitter = "0.27"
tree-sitter-bibtex = { git = "https://github.com/henryhchchc/tree-sitter-bibtex.git", branch = "master" }
tree-sitter-c = "0.24.2"
tree-sitter-cpp = "0.23.4"
tree-sitter-javascript = "0.25.0"
tree-sitter-language = "0.1.7"
tree-sitter-latex = { git = "https://github.com/henryhchchc/tree-sitter-latex.git", branch = "self-use" }
tree-sitter-mlir = { git = "https://github.com/henryhchchc/tree-sitter-mlir.git", branch = "master" }
tree-sitter-qmljs = { git = "https://github.com/henryhchchc/tree-sitter-qmljs.git", branch = "master" }
tree-sitter-ruby = "0.23.1"
tree-sitter-rust = "0.24.2"
tree-sitter-solidity = "1.2.13"
tree-sitter-systemverilog = "0.4.0"
# tree-sitter-verilog = { git = "https://github.com/gmlarumbe/tree-sitter-systemverilog.git", branch = "dev", rev = "8537224191c086be0b3bc176a57298c47fa9d49c" } # ASE-submission revision
tree-sitter-toml-ng = "0"
tuple_list = "0.1"
walkdir = "2.5.0"
zstd = { version = "0.13", default-features = false }

[workspace.lints.clippy]
enum_glob_use = { level = "allow", priority = 1 }
pedantic = "warn"

[patch.crates-io]
# This is a custom version with tweaks required by lsp-fuzz (e.g., `Hash` trait implementations)
lsp-types = {
  git = "https://github.com/henryhchchc/lsp-types.git",
  rev = "00b517e1936150cd8ab7a02aeb602c2a5fe66a46"
}

[profile.release]
opt-level = 3
debug = true
lto = true
codegen-units = 1
