[package]
name = "lsp-fuzz-tree-sitter-grammar"
version.workspace = true
edition.workspace = true

[dependencies]
hashbrown.workspace = true
indexmap = { workspace = true, features = ["serde"] }
regex.workspace = true
regex-syntax.workspace = true
rustc-hash.workspace = true
serde = { workspace = true, features = ["derive"] }
# Grammar rule insertion order determines the implicit start symbol.
serde_json = { workspace = true, features = ["preserve_order"] }
thiserror.workspace = true
