lints.workspace = true

[package]
name = "lsp-fuzz-cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ciborium.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
core_affinity.workspace = true
ctrlc.workspace = true
derive-new.workspace = true
itertools.workspace = true
libafl = { workspace = true, features = ["clap"] }
libafl_bolts = { workspace = true, features = ["std"] }
libcasr = { workspace = true, features = ["serde"] }
lsp-fuzz.workspace = true
lsp-fuzz-grammars.workspace = true
memmap2.workspace = true
nix = { workspace = true, features = ["signal"] }
num_cpus.workspace = true
os_pipe.workspace = true
rayon.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
tracing = { workspace = true, features = ["attributes", "std"] }
tuple_list.workspace = true
walkdir.workspace = true
zstd = { workspace = true, features = ["zstdmt"] }

[dependencies.tracing-subscriber]
workspace = true
features = ["ansi", "chrono", "env-filter", "fmt"]

[features]
profiling = ["lsp-fuzz/profiling"]
