lints.workspace = true

[package]
name = "lsp-fuzz"
version.workspace = true
edition.workspace = true

[dependencies]
ahash.workspace = true
anyhow.workspace = true
bitflags.workspace = true
ciborium.workspace = true
const-str.workspace = true
derive-new.workspace = true
dot-structures.workspace = true
fastbloom = { workspace = true, features = ["serde", "std"] }
fluent-uri.workspace = true
graphviz-rust.workspace = true
indexmap = { workspace = true, features = ["serde"] }
itertools.workspace = true
kmp.workspace = true
libc.workspace = true
lsp-fuzz-grammars.workspace = true
lsp-fuzz-tree-sitter-grammar.workspace = true
lsp-types = { workspace = true, features = ["hash"] }
ordermap = { workspace = true, features = ["serde"] }
os_pipe.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
smallvec = { workspace = true, features = ["const_generics"] }
static_assertions.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing = { workspace = true, features = ["std"] }
trait-gen.workspace = true
tree-sitter.workspace = true
tuple_list.workspace = true

[dependencies.derive_more]
workspace = true
features = [
  "constructor",
  "debug",
  "deref",
  "deref_mut",
  "display",
  "from",
  "into",
  "into_iterator",
]

[dependencies.libafl]
workspace = true
features = ["casr", "derive", "serdeany_autoreg"]

[dependencies.libafl_bolts]
workspace = true
features = ["derive", "serdeany_autoreg", "std"]

[dependencies.nix]
workspace = true
features = ["fs", "poll", "resource", "signal"]

[features]
profiling = ["libafl/introspection"]
